version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    env_file:
      - ./env/api.env.example
    ports:
      - "8000:8080"
    volumes:
      - ../apps/api/src:/workspace/apps/api/src:delegated
      - ../packages/common:/workspace/packages/common:delegated
    restart: unless-stopped
