[project]
name = "conectasenai-common"
version = "0.1.0"
description = "Utilitários compartilhados do Conecta-SENAI"
authors = [
    { name = "Conecta-SENAI" }
]
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = []

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["conectasenai_common"]

[tool.ruff]
line-length = 120
