"""Feature: Add instructor rate and cost center modules

Revision ID: 05455c6ca018
Revises: 
Create Date: 2025-07-12 16:23:15.695155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05455c6ca018'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrutores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custo_hora', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrutores', schema=None) as batch_op:
        batch_op.drop_column('custo_hora')

    # ### end Alembic commands ###
