"""Adiciona campo descricao em RateioConfig

Revision ID: 4b18c0688af2
Revises: 
Create Date: 2025-07-15 23:32:31.062628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '4b18c0688af2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = inspect(bind)
    if 'rateio_configs' in inspector.get_table_names():
        cols = [c['name'] for c in inspector.get_columns('rateio_configs')]
        if 'descricao' not in cols:
            with op.batch_alter_table('rateio_configs', schema=None) as batch_op:
                batch_op.add_column(sa.Column('descricao', sa.String(length=255), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rateio_configs', schema=None) as batch_op:
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
