"""add indexes to frequently filtered columns

Revision ID: 4e1e4aa55146
Revises: 9fd848c63563
Create Date: 2025-08-09 02:13:41.039893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1e4aa55146'
down_revision: Union[str, Sequence[str], None] = '9fd848c63563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agendamentos_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamentos_laboratorio'), ['laboratorio'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamentos_turno'), ['turno'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamentos_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('log_lancamentos_rateio_instrutor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_lancamentos_rateio_instrutor_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_lancamentos_rateio_instrutor_usuario'), ['usuario'], unique=False)

    with op.batch_alter_table('logs_agendamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_agendamentos_data_agendamento'), ['data_agendamento'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_agendamentos_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_agendamentos_tipo_acao'), ['tipo_acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_agendamentos_usuario'), ['usuario'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_agendamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_agendamentos_usuario'))
        batch_op.drop_index(batch_op.f('ix_logs_agendamentos_tipo_acao'))
        batch_op.drop_index(batch_op.f('ix_logs_agendamentos_timestamp'))
        batch_op.drop_index(batch_op.f('ix_logs_agendamentos_data_agendamento'))

    with op.batch_alter_table('log_lancamentos_rateio_instrutor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_lancamentos_rateio_instrutor_usuario'))
        batch_op.drop_index(batch_op.f('ix_log_lancamentos_rateio_instrutor_timestamp'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity'))

    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agendamentos_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_agendamentos_turno'))
        batch_op.drop_index(batch_op.f('ix_agendamentos_laboratorio'))
        batch_op.drop_index(batch_op.f('ix_agendamentos_data'))

    # ### end Alembic commands ###
