# flake8: noqa
"""Planejamento de Treinamentos

Revision ID: 5339db72d1b1
Revises: 9fd848c63563
Create Date: 2025-08-14 14:27:30.692802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5339db72d1b1'
down_revision: Union[str, Sequence[str], None] = '9fd848c63563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planejamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('turno', sa.Enum('MANHA', 'TARDE', 'NOITE', name='turno_enum'), nullable=False),
    sa.Column('carga_horas', sa.Integer(), nullable=True),
    sa.Column('modalidade', sa.Enum('Presencial', 'Online', name='modalidade_enum'), nullable=True),
    sa.Column('treinamento', sa.String(length=255), nullable=False),
    sa.Column('instrutor_id', sa.Integer(), nullable=False),
    sa.Column('local', sa.String(length=255), nullable=True),
    sa.Column('cliente', sa.String(length=120), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Planejado', 'Confirmado', 'Cancelado', name='status_enum'), nullable=False),
    sa.Column('origem', sa.Enum('Manual', 'Importado', name='origem_enum'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', 'turno', 'instrutor_id', name='uq_planejamento_slot_instrutor')
    )
    with op.batch_alter_table('planejamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planejamento_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_planejamento_instrutor_id'), ['instrutor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planejamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planejamento_instrutor_id'))
        batch_op.drop_index(batch_op.f('ix_planejamento_data'))

    op.drop_table('planejamento')
    # ### end Alembic commands ###
