"""Reconstroi modulo de treinamentos

Revision ID: fa7b986444aa
Revises: 67a52a1d4e3a
Create Date: 2025-07-20 12:11:16.465750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7b986444aa'
down_revision = '67a52a1d4e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
