"""Merge planejamento branch

Revision ID: merge_planejamento_branch
Revises: c68944a9fc4a, d1b2c3d4e5f6
Create Date: 2024-05-21 10:00:00.000000

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'merge_planejamento_branch'
down_revision: Union[str, Sequence[str], None] = (
    'c68944a9fc4a',
    'd1b2c3d4e5f6',
)
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
