name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pytest flake8 bandit

    - name: Lint with flake8
      run: flake8 --max-line-length=120 --exit-zero

    - name: Security scan with bandit
      run: bandit -r src -ll

    - name: Run tests
      run: pytest
